from app.agents.state import AgentState
from app.agents.tools import (
    get_sales_summary,
    get_inventory_status,
    detect_anomalies,
    get_forecast_accuracy
)
from app.services.llm import call_claude, build_system_prompt
from app.core.logger import get_logger
import json

logger = get_logger(__name__)

def collect_sales_data(state: AgentState) -> AgentState:
    logger.info("Agent: collecting sales data")
    sales = get_sales_summary(days=7)
    state["data_collected"]["sales"] = sales
    state["messages"] = state["messages"] + [
        f"Collected sales data: ${sales['total_revenue']} revenue over last 7 days"
    ]
    state["current_step"] = "sales_collected"
    state["iteration_count"] += 1
    return state

def collect_inventory_data(state: AgentState) -> AgentState:
    logger.info("Agent: collecting inventory data")
    inventory = get_inventory_status()
    state["data_collected"]["inventory"] = inventory
    state["messages"] = state["messages"] + [
        f"Inventory check: {inventory['total_alerts']} alerts, "
        f"{inventory['healthy_items']} healthy items"
    ]
    state["current_step"] = "inventory_collected"
    state["iteration_count"] += 1
    return state

def detect_anomaly_node(state: AgentState) -> AgentState:
    logger.info("Agent: detecting anomalies")
    anomaly_result = detect_anomalies()
    state["data_collected"]["anomalies"] = anomaly_result
    if anomaly_result["anomalies"]:
        state["anomalies_found"] = anomaly_result["anomalies"]
        state["messages"] = state["messages"] + [
            f"Found {anomaly_result['total_anomalies']} anomalies requiring attention"
        ]
    else:
        state["messages"] = state["messages"] + [
            "No significant anomalies detected"
        ]
    state["current_step"] = "anomalies_detected"
    state["iteration_count"] += 1
    return state

def generate_recommendations(state: AgentState) -> AgentState:
    logger.info("Agent: generating recommendations")
    recommendations = []
    inventory = state["data_collected"].get("inventory", {})
    if inventory.get("total_alerts", 0) > 0:
        for alert in inventory["alerts"][:3]:
            recommendations.append(
                f"Reorder {alert['item']} at {alert.get('location', 'all locations')} "
                f"— current stock {alert['current_stock']} below reorder point "
                f"{alert['reorder_point']}"
            )
    for anomaly in state.get("anomalies_found", [])[:3]:
        if anomaly["direction"] == "down":
            recommendations.append(
                f"Investigate {anomaly['category']} revenue decline "
                f"of {abs(anomaly['change_pct'])}% versus previous week"
            )
        else:
            recommendations.append(
                f"Capitalize on {anomaly['category']} revenue increase "
                f"of {anomaly['change_pct']}% — consider increasing stock"
            )
    if not recommendations:
        recommendations.append(
            "Operations running normally — maintain current strategy"
        )
    state["recommendations"] = recommendations
    state["messages"] = state["messages"] + [
        f"Generated {len(recommendations)} recommendations"
    ]
    state["current_step"] = "recommendations_generated"
    state["iteration_count"] += 1
    return state

def generate_report(state: AgentState) -> AgentState:
    logger.info("Agent: generating final report with Claude")
    sales = state["data_collected"].get("sales", {})
    inventory = state["data_collected"].get("inventory", {})
    anomalies = state["data_collected"].get("anomalies", {})
    prompt = f"""You are an AI operations agent that has just completed
an autonomous analysis of campus food service operations.

Here is the data you collected:

SALES SUMMARY (last 7 days):
Total Revenue: ${sales.get('total_revenue', 0)}
By Category: {json.dumps(sales.get('by_category', []), indent=2)}

INVENTORY STATUS:
Total Alerts: {inventory.get('total_alerts', 0)}
Alerts: {json.dumps(inventory.get('alerts', []), indent=2)}

ANOMALIES DETECTED:
{json.dumps(anomalies.get('anomalies', []), indent=2)}

AGENT RECOMMENDATIONS:
{chr(10).join(f'- {r}' for r in state.get('recommendations', []))}

AGENT STEPS TAKEN:
{chr(10).join(state.get('messages', []))}

Generate a concise autonomous agent report with:
1. AGENT ANALYSIS SUMMARY (what the agent found)
2. CRITICAL FINDINGS (top 3 issues)
3. RECOMMENDED ACTIONS (specific steps)
4. CONFIDENCE LEVEL (high/medium/low with reason)

Keep it under 250 words. Be direct and specific."""
    result = call_claude(
        prompt=prompt,
        system_prompt=build_system_prompt(),
        max_tokens=500
    )
    state["report"] = result["content"]
    state["messages"] = state["messages"] + ["Final report generated by Claude"]
    state["current_step"] = "report_generated"
    state["should_continue"] = False
    state["iteration_count"] += 1
    return state

def should_continue_check(state: AgentState) -> str:
    if state["iteration_count"] > 10:
        return "end"
    if not state["should_continue"]:
        return "end"
    return "continue"